#!/usr/bin/env python3
"""Helper script for the story-driven apply workflow.

Subcommands:
  parse-tasks <tasks.md> [--json]
      Parse an OpenSpec tasks.md into a structured list of task groups/tasks.
  generate <change> [--root <changeRoot>] [--def <stories.yaml>]
      Read a story definition, validate it, and write stories.md +
      story-seed.cypher into the change root.
  sync-tasks <change> <storyId> [--root <changeRoot>] [--def <stories.yaml>]
      Mark the tasks referenced by a story as done in tasks.md.
  append-state <change> <text> [--root <changeRoot>]
      Append a compact summary line to <changeRoot>/.story-state.md.
"""

import argparse
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    yaml = None


def default_change_root(change: str, root: str | None) -> Path:
    if root:
        return Path(root)
    return Path("openspec/changes") / change


def parse_tasks(tasks_path: Path):
    """Return {groups: [{title, tasks: [{num, desc}]}], all: [desc]} from a tasks.md."""
    groups = []
    current = None
    for line in tasks_path.read_text().splitlines():
        m = re.match(r"^##\s+(.+)$", line)
        if m:
            current = {"title": m.group(1).strip(), "tasks": []}
            groups.append(current)
            continue
        m = re.match(r"^-\s+\[[ xX]\]\s+(.+)$", line)
        if m and current is not None:
            task = m.group(1).strip()
            current["tasks"].append({"num": len(current["tasks"]) + 1, "desc": task})
    all_tasks = [t["desc"] for g in groups for t in g["tasks"]]
    return {"groups": groups, "all": all_tasks}


def load_stories(def_path: Path, change: str):
    if not def_path.exists():
        sys.exit(f"error: story definition not found: {def_path}")
    if yaml is None:
        sys.exit("error: PyYAML is required to read story definitions")
    data = yaml.safe_load(def_path.read_text())
    if not isinstance(data, dict):
        sys.exit("error: story definition must be a YAML mapping")
    if data.get("change") != change:
        sys.exit(
            f"error: definition change {data.get('change')!r} != requested {change!r}"
        )
    stories = data.get("stories", [])
    if not isinstance(stories, list) or not stories:
        sys.exit("error: story definition has no stories")
    return stories


def validate_stories(stories, tasks):
    ids = [s["id"] for s in stories]
    if len(ids) != len(set(ids)):
        sys.exit("error: duplicate story ids")
    for s in stories:
        if not re.match(r"^[a-z0-9]+(-[a-z0-9]+)*$", s["id"]):
            sys.exit(f"error: story id {s['id']!r} is not kebab-case")
        for field in ("title", "description"):
            if not s.get(field):
                sys.exit(f"error: story {s['id']!r} missing {field}")
        ac = s.get("acceptanceCriteria", [])
        if not isinstance(ac, list) or not (1 <= len(ac) <= 3):
            sys.exit(f"error: story {s['id']!r} must have 1-3 acceptance criteria")
        for ref in s.get("dependsOn", []):
            if ref not in ids:
                sys.exit(f"error: story {s['id']!r} depends on unknown story {ref!r}")
        for ref in s.get("taskRefs", []):
            if ref not in tasks:
                sys.exit(f"error: story {s['id']!r} taskRef not found in tasks.md: {ref!r}")

    covered = [ref for s in stories for ref in s.get("taskRefs", [])]
    missing = [t for t in tasks if t not in covered]
    orphans = [r for r in covered if r not in tasks]
    if missing:
        sys.exit(f"error: tasks not covered by any story: {missing}")
    if orphans:
        sys.exit(f"error: taskRefs not in tasks.md: {orphans}")

    visited = {}

    def visit(sid, chain):
        if sid in visited:
            return
        if sid in chain:
            sys.exit(f"error: dependency cycle: {chain + [sid]}")
        for dep in next(s["dependsOn"] for s in stories if s["id"] == sid):
            visit(dep, chain + [sid])
        visited[sid] = True

    for s in stories:
        visit(s["id"], [])


def cypher_str(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def write_stories_md(stories, change, root: Path):
    lines = [
        f"# Stories — {change}",
        "",
        "This file is generated by `story-driver.py generate` — do not edit by hand.",
        "",
    ]
    for i, s in enumerate(stories, 1):
        lines.append(f"## Story {i}: {s['id']} — {s['title']}")
        lines.append("")
        lines.append(s["description"].strip())
        lines.append("")
        lines.append("**Acceptance criteria:**")
        for ac in s["acceptanceCriteria"]:
            lines.append(f"- {ac}")
        lines.append("")
        deps = s.get("dependsOn", [])
        lines.append(
            "**Dependencies:** "
            + (", ".join(deps) if deps else "none")
        )
        lines.append("")
    (root / "stories.md").write_text("\n".join(lines))


def write_seed(stories, change, root: Path):
    parts = [
        "// Story graph seed for change",
        f'// change: {cypher_str(change)}',
        "// Idempotent: each statement uses MERGE; safe to re-run.",
        f"MERGE (c:Change {{name: {cypher_str(change)}}});",
    ]
    for s in stories:
        sets = [
            f's.title = {cypher_str(s["title"])}',
            f's.description = {cypher_str(s["description"].strip())}',
            "s.acceptanceCriteria = "
            + json.dumps(s["acceptanceCriteria"], ensure_ascii=False),
            "s.taskRefs = " + json.dumps(s.get("taskRefs", []), ensure_ascii=False),
            's.status = "pending"',
        ]
        parts += [
            "",
            f'MERGE (s:Story {{id: {cypher_str(s["id"])}, change: {cypher_str(change)}}})',
            "ON CREATE SET " + ", ".join(sets) + ";",
            f'MATCH (c:Change {{name: {cypher_str(change)}}}),',
            f'      (s:Story {{id: {cypher_str(s["id"])}, change: {cypher_str(change)}}})',
            "MERGE (c)-[:HAS_STORY]->(s);",
        ]
    for s in stories:
        for dep in s.get("dependsOn", []):
            parts += [
                "",
                f'MATCH (a:Story {{id: {cypher_str(s["id"])}, change: {cypher_str(change)}}})',
                f'MATCH (b:Story {{id: {cypher_str(dep)}, change: {cypher_str(change)}}})',
                "MERGE (a)-[:DEPENDS_ON]->(b);",
            ]
    (root / "story-seed.cypher").write_text("\n".join(parts))


def sync_tasks(change, story_id, root: Path, def_path: Path):
    stories = load_stories(def_path, change)
    story = next((s for s in stories if s["id"] == story_id), None)
    if story is None:
        sys.exit(f"error: unknown story {story_id!r} in {def_path}")
    tasks_path = root / "tasks.md"
    if not tasks_path.exists():
        sys.exit(f"error: tasks.md not found: {tasks_path}")
    refs = story.get("taskRefs", [])
    if not refs:
        return 0
    lines = tasks_path.read_text().splitlines(keepends=True)
    toggled = 0
    for i, line in enumerate(lines):
        m = re.match(r"^(-\s+)\[ \]\s+(.*)$", line)
        if not m:
            continue
        desc = m.group(2).strip()
        if desc in refs:
            lines[i] = f"{m.group(1)}[x] {desc}\n"
            toggled += 1
    tasks_path.write_text("".join(lines))
    return toggled


def append_state(change, text, root: Path):
    state = root / ".story-state.md"
    if not state.exists():
        state.write_text(f"# Story state — {change}\n")
    with state.open("a") as f:
        f.write(f"- {text}\n")


def cmd_parse(args):
    tasks_path = Path(args.tasks)
    data = parse_tasks(tasks_path)
    if args.json:
        print(json.dumps(data, indent=2))
    else:
        for g in data["groups"]:
            print(f"## {g['title']}")
            for t in g["tasks"]:
                print(f"- [ ] {t['desc']}")


def cmd_generate(args):
    root = default_change_root(args.change, args.root)
    def_path = Path(args.def_path) if args.def_path else root / "stories.yaml"
    tasks_path = root / "tasks.md"
    if not tasks_path.exists():
        sys.exit(f"error: tasks.md not found: {tasks_path}")
    tasks = parse_tasks(tasks_path)["all"]
    stories = load_stories(def_path, args.change)
    validate_stories(stories, tasks)
    write_stories_md(stories, args.change, root)
    write_seed(stories, args.change, root)
    print(f"wrote {root / 'stories.md'}")
    print(f"wrote {root / 'story-seed.cypher'}")


def cmd_sync(args):
    root = default_change_root(args.change, args.root)
    def_path = Path(args.def_path) if args.def_path else root / "stories.yaml"
    n = sync_tasks(args.change, args.story_id, root, def_path)
    print(f"toggled {n} task(s) for story {args.story_id}")


def cmd_append(args):
    root = default_change_root(args.change, args.root)
    append_state(args.change, args.text, root)
    print(f"appended to {root / '.story-state.md'}")


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    sub = p.add_subparsers(dest="command", required=True)

    p_parse = sub.add_parser("parse-tasks")
    p_parse.add_argument("tasks", help="path to tasks.md")
    p_parse.add_argument("--json", action="store_true")
    p_parse.set_defaults(func=cmd_parse)

    p_gen = sub.add_parser("generate")
    p_gen.add_argument("change")
    p_gen.add_argument("--root")
    p_gen.add_argument("--def", dest="def_path", help="path to stories.yaml (default: <root>/stories.yaml)")
    p_gen.set_defaults(func=cmd_generate)

    p_sync = sub.add_parser("sync-tasks")
    p_sync.add_argument("change")
    p_sync.add_argument("story_id")
    p_sync.add_argument("--root")
    p_sync.add_argument("--def", dest="def_path")
    p_sync.set_defaults(func=cmd_sync)

    p_append = sub.add_parser("append-state")
    p_append.add_argument("change")
    p_append.add_argument("text")
    p_append.add_argument("--root")
    p_append.set_defaults(func=cmd_append)

    args = p.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
